# Deploy Configuration for Motia Framework
# This file centralizes deploy settings and package information

packages:
  - name: '@motiadev/core'
    critical: true
  - name: '@motiadev/workbench'
    critical: true
  - name: '@motiadev/stream-client'
    critical: false
  - name: '@motiadev/stream-client-browser'
    critical: false
  - name: '@motiadev/stream-client-node'
    critical: false
  - name: '@motiadev/stream-client-react'
    critical: false
  - name: 'motia'
    critical: true
  - name: '@motiadev/test'
    critical: false

npm_tags:
  pre_release: 'pre-release'
  stable: 'latest'

environments:
  test:
    name: 'staging'
    url: 'https://staging.motia.dev'
  production:
    name: 'production'
    url: 'https://motia.dev'

notifications:
  teams:
    - '@motiadev/core-team'
  labels:
    success: ['release', 'deployed']
    failure: ['release-failure', 'high-priority', 'bug']

timeouts:
  e2e_tests: 30 # minutes
  deploy_total: 60 # minutes

retry:
  e2e_tests: 2
  npm_publish: 3
