name: Deploy Motia Docker Image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy'
        required: false
  push:
    branches:
      - main
    paths:
      - 'packages/docker/Dockerfile'

env:
  DOCKER_MOTIA_ORG: motiadev
  DOCKER_IMAGE_NAME: motia

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name || github.ref }}

      - name: Get short SHA
        id: short-sha
        run: |
          if [ -n "${{ github.event.pull_request.head.sha }}" ]; then
            echo "sha=$(echo ${{ github.event.pull_request.head.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT
          else
            echo "sha=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        env:
          GITHUB_SHA: ${{ github.event.inputs.environment|| steps.short-sha.outputs.sha }}
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.DOCKER_MOTIA_ORG }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.event.inputs.version || env.GITHUB_SHA }}
            ${{ env.DOCKER_MOTIA_ORG }}/${{ env.DOCKER_IMAGE_NAME }}:latest
          file: packages/docker/config/Dockerfile
          context: packages/docker/config
